### ISSUE TITLE
missing images in docs: querying_data.md

### ISSUE THREAD

**Issue by jacarrico** [phyloviz/phyloviz.github.io#2]
Images missing in : 

Query examples:
- Table view with selections
  ![_Table_ view with selections](_images/TableViewRegex.png)
- Query results Chart
  ![query results Chart](_images/TableViewPie.png)
- Results on Display Tab 
  ![results on _Display_ tab](_images/TVRdisplay.png)

**Comment by aplf** [comment]
Fixed.
